on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  setup:
   - name: Setup Node.js environment
     uses: actions/setup-node@v3.6.0
      run:|
        node html.js

    
